---
- name: restart apache
  service:
    name: "{{ apache_service }}"
    state: restarted
  when: ansible_connection != 'docker' # Standard behavior

- name: reload apache
  service:
    name: "{{ apache_service }}"
    state: reloaded
  when: ansible_connection != 'docker'

- name: restart mariadb
  service:
    name: mariadb
    state: restarted
  when: ansible_connection != 'docker'
